import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "formulario",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`antialiased `}
      >
        
        {children}
      </body>
    </html>
  );
}
